<header>
    <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="navbar-brand" href="/home"><img alt="Logo" src="/resources/icons/calendar.ico" height="32px"></a>
                <a class="nav-item nav-link <?= strpos($_SERVER['REQUEST_URI'], "home") ? "active" : "" ?>" href="/home">Home</a>

                <?php if (isset($_SESSION['USER_ID'])): ?>
                    <!-- User logged in -->
                    <a class="nav-item nav-link <?= strpos($_SERVER['REQUEST_URI'], "event") ? "active" : "" ?>" href="/event-overview">Events</a>
                    <a class="nav-item nav-link <?= strpos($_SERVER['REQUEST_URI'], "profile") ? "active" : "" ?>" href="/profile">My Profile</a>
                    <a class="nav-item nav-link <?= strpos($_SERVER['REQUEST_URI'], "chat") ? "active" : "" ?>" href="/chat">Chat</a>
                    <a class="nav-item nav-link" href="/logout">Logout</a>
                <?php else: ?>
                    <!-- User not logged in -->
                    <a class="nav-item nav-link" href="/login">Login</a>
                    <a class="nav-item nav-link" href="/register">Register</a>
                <?php endif; ?>
            </div>
        </div>
    </nav>
</header>