<header>
    <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="navbar-brand" href="/home"><img alt="Logo" src="/resources/icons/calendar.ico" height="32px"></a>
                <a class="nav-item nav-link <?= strpos($_SERVER['REQUEST_URI'], "event") ? "active" : "" ?>" href="/event-overview">Events</a>

<!--                if user is logged in, display Profile button, else display login button-->
                <?php if (isset($_SESSION['USER_ID'])) {?>
                    <a class="nav-item nav-link" <?= strpos($_SERVER['REQUEST_URI'], "profile") ? "active" : "" ?> href="/profile">My Profile</a>
                    <a class="nav-item nav-link" href="/logout">Logout</a>
                <?php }else{ ?>
                    <a class="nav-item nav-link" href="/login">Login</a>
                <?php } ?>
            </div>
        </div>
    </nav>
</header>