<html lang="en">
    <head>
        <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/shared.phtml" ?>
    </head>
    <body>
        <div class="container min-vh-80">
            <h1>Email Confirmation</h1>
            <?php if(isset($isError) && $isError): ?>
                <div class="alert alert-danger" role="alert">
                    <p class="text-danger"><?php echo $_SESSION['CONFIRM_ERROR']; ?></p>
                </div>
            <?php endif ?>

            <?php if(isset($isSuccess) && $isSuccess): ?>
                <div class="alert alert-success" role="alert">
                    <p class="text-success"><?php echo $_SESSION["CONFIRM_SUCCESS"]; ?></p>
                </div>
            <?php endif ?>
            <div>
                <a href="/login">
                    <button class="btn btn-primary" >To Login</button>
                </a>
                <a href="/register">
                    <button class="btn btn-secondary" >Back to Register</button>
                </a>
            </div>
        </div>
        <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/footer/footer.phtml" ?>
    </body>
</html>
