<html lang="en">
<head>
    <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/shared.phtml" ?>
</head>
<body>
<div class="container min-vh-80">
    <h1>Email Confirmation</h1>
    <?php if (isset($isError) && $isError): ?>
        <div class="alert alert-danger" role="alert">
            <p class="text-danger"><?php echo $_SESSION['CONFIRM_ERROR']; ?></p>
        </div>
    <?php endif ?>

    <?php if (isset($isSuccess) && $isSuccess): ?>
        <div class="alert alert-success" role="alert">
            <p class="text-success"><?php echo $_SESSION["CONFIRM_SUCCESS"]; ?></p>
        </div>
    <?php endif ?>

    <?php if (isset($_SESSION['USER_ID'])): ?>
        <!-- User logged in -->
        <div>
            <a href="/home">
                <button class="btn btn-primary">To Homepage</button>
            </a>
        </div>
    <?php else: ?>
        <!-- User not logged in -->
        <div>
            <a href="/login">
                <button class="btn btn-primary">To Login</button>
            </a>
            <a href="/register">
                <button class="btn btn-secondary">Back to Register</button>
            </a>
        </div>
    <?php endif; ?>
</div>
<?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/footer/footer.phtml" ?>
</body>
</html>
