<!DOCTYPE html>
<html lang="en">
<head>
    <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/shared.phtml" ?>
</head>
<body>
<?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/header/header.phtml" ?>


<div class="container min-vh-80">
    <div class="col-sm-8">
        <h1>Reset password</h1>

        <?php if (isset($isError) && $isError): ?>
            <div class="alert alert-danger" role="alert">
                <p class="text-danger"><?= $_SESSION["PASSWORD_SAVE_ERROR"] ?></p>
            </div>
        <?php endif ?>

        <?php if (isset($isSuccess) && $isSuccess): ?>
            <div class="alert alert-success" role="alert">
                <p class="text-success"><?= $_SESSION["PASSWORD_SAVE_SUCCESS"] ?></p>
            </div>
        <?php endif ?>

        <form method="post">

            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" name="password" maxlength="32" class="form-control"><br/>
            </div>
            <div class="form-group">
                <label for="password_repeat">Repeat password</label>
                <input type="password" name="password_repeat" maxlength="32" class="form-control"><br/>
            </div>
            <div class="row">
                <button type="submit" class="btn btn-primary" name="update" style="margin-right: 10px">Save
                </button>
                <a href="/login" class="btn btn-secondary">Cancel</a>
            </div>
        </form>
    </div>
</div>
<?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/footer/footer.phtml" ?>
</body>
</html>
