<!DOCTYPE html>
<html lang="en">
    <head>
        <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/shared.phtml" ?>
        <script type="text/javascript" src="/views/event-create/event-create.js"></script>
        <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.1/js/bootstrap-datepicker.js"></script>
        <link href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.1/css/datepicker.css" rel="stylesheet"/>
    </head>
    <body>
        <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/header/header.phtml" ?>
        <div class="container min-vh-80">
            <h1><?php if( isset($pageTitle)) echo($pageTitle)?></h1><br>
            <p>Please enter following values to create an event.</p>

            <?php if (isset($isError) && $isError): ?>
                <div class="alert alert-danger" role="alert">
                    <p class="text-danger"><?=$_SESSION["EVENT_CREATE_ERROR"]?></p>
                </div>
            <?php endif ?>

            <?php if(isset($isSuccess) && $isSuccess): ?>
                <div class="alert alert-success" role="alert">
                    <p class="text-success"><?=$_SESSION["EVENT_CREATE_SUCCESS"]?></p>
                </div>
            <?php endif ?>

            <form method="post">
                <div class="form-group">
                    <label for="event-create-title">Title*</label>
                    <input id="event-create-title" type="text" name="title" maxlength="32" required class="form-control"><br/>
                </div>
                <div class="form-group">
                    <label for="event-create-description">Description*</label>
                    <textarea id="event-create-description" name="description" maxlength="256" required class="form-control"></textarea><br/>
                </div>
                <div class="form-group">
                    <label for="event-create-location">Location</label>
                    <input id="event-create-location" type="text" name="location" maxlength="32" class="form-control"><br/>
                </div>
                <div class="form-group">
                    <label for="event-create-date">Date*</label>
                    <input id="event-create-date" name="date" placeholder="yyyy-mm-dd" required class="form-control datepicker"><br/>
                </div>
                <div class="form-group">
                    <label for="event-create-time">Time</label>
                    <input id="event-create-time" type="text" name="time" pattern="^([0-1][0-9]|[2][0-3]):([0-5][0-9])$" placeholder="hh:mm" class="form-control"><br/>
                </div>
                <div class="form-group">
                    <label for="event-create-visibility">Visibility*</label>
                    <select id="event-create-visibility" name="visibility" required class="form-control">
                        <?php foreach(\models\enums\Visibility::staticProperties() as $value) {
                                echo "<option>".$value."</option>";
                        } ?>
                    </select><br/>
                </div>
                <div class="form-group">
                    <label for="event-create-maximum-attendees">Maximum Attendees</label>
                    <input id="event-create-maximum-attendees" type="number" name="maximum_attendees" class="form-control"><br/>
                </div>
                <div class="form-group">
                    <label for="event-create-price">Price</label>
                    <input id="event-create-price" type="number" step="0.01" name="price" class="form-control"><br/>
                </div>
                <p class="text-danger">*These fields are required.</p>
                <button type="submit" class="btn btn-primary mb-3">Create Event</button>
            </form>
        </div>
        <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/footer/footer.phtml" ?>
    </body>
</html>