<!DOCTYPE html>
<html lang="en">
<head>
    <title>Create Event</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <script type="text/javascript" src="/resources/assets/bootstrap/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/resources/assets/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="/resources/assets/jqueryui/jquery-ui.js"></script>
    <script type="text/javascript" src="/views/event-create/event-create.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.1/js/bootstrap-datepicker.js"></script>
    <link href="/resources/assets/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.1/css/datepicker.css" rel="stylesheet"/>
</head>
<body>
    <div class="container">
        <h1>Create Event</h1><br>
        <p>Please enter following values to create an event.</p>

        <?php if (isset($isCreateEventError) && $isCreateEventError): ?>
            <div class="alert alert-danger" role="alert">
                <p class="text-danger"><?php echo $_SESSION["CREATE_EVENT_ERROR"]; ?></p>
            </div>
        <?php endif ?>

        <form method="post" target="RegisterController.php">
            <div class="form-group">
                <label for="event-create-title">Title*</label>
                <input id="event-create-title" type="text" name="title" required class="form-control"><br/>
            </div>
            <div class="form-group">
                <label for="event-create-description">Description*</label>
                <input id="event-create-description" type="text" name="description" required class="form-control"><br/>
            </div>
            <div class="form-group">
                <label for="event-create-location">Location</label>
                <input id="event-create-location" type="text" name="location" class="form-control"><br/>
            </div>
            <div class="form-group">
                <label for="event-create-date">Date*</label>
                <input id="event-create-date" name="date" placeholder="yyyy-mm-dd" required class="form-control datepicker"><br/>
            </div>
            <div class="form-group">
                <label for="event-create-time">Time</label>
                <input id="event-create-time" type="time" name="time" class="form-control"><br/>
            </div>
            <div class="form-group">
                <label for="event-create-visibility">Visibility*</label>
                <select id="event-create-visibility" name="visibility" required class="form-control">
                    <option selected>Choose...</option>
                </select><br/>
            </div>
            <div class="form-group">
                <label for="event-create-maximum-attendees">Maximum Attendees</label>
                <input id="event-create-maximum-attendees" type="number" name="maximum_attendees" class="form-control"><br/>
            </div>
            <div class="form-group">
                <label for="event-create-price">Price</label>
                <input id="event-create-price" type="number" name="price" class="form-control"><br/>
            </div>
            <p class="text-danger">*These fields are required.</p>
            <button type="submit" class="btn btn-primary">Create Event</button>
        </form>
    </div>
</body>
</html>