version: '3.2'
services:
  db:
    container_name: pg-database
    image: postgres:12.2
    ports:
    - 5433:5432
    networks:
      development:
    volumes:
    - database:/var/lib/postgres/data
    - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: "event-booking"
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "dev"

  web:
    container_name: web-server
    image: event-booking-apache:2020
    ports:
    - 8080:80
    networks:
      development:
    depends_on:
      - db
    volumes:
    - type: bind
      source: "./src"
      target: "/var/www/html"
    - webserver:/data

  smtp:
    container_name: smtp-server
    image: namshi/smtp:latest
    ports:
    - "2525:25"
    networks:
      development:
    environment:
      MAILNAME: "dhbw-event.com"

  websocket:
    container_name: websocket-server
    image: event-booking-websocket:2020
    ports:
    -  8089:8089
    networks:
      development:

volumes:
  database:
  webserver:

networks:
  development:
    driver: bridge
