<!-- Needed on every page -->
<title><?= isset($pageTitle) ? $pageTitle : "Event Booking"?></title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta charset="utf-8">
<!-- Bootstrap (needs jQuery) -->
<script type="text/javascript" src="/resources/assets/jquery/jquery.min.js"></script>
<script type="text/javascript" src="/resources/assets/jqueryui/jquery-ui.js"></script>
<script type="text/javascript" src="/resources/assets/bootstrap/js/bootstrap.min.js"></script>
<link href="/resources/assets/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<!-- custom styles for site structure -->
<link href="/views/shared/shared.css" rel="stylesheet">
<link href="/views/shared/header/header.css" rel="stylesheet">
<link href="/views/shared/footer/footer.css" rel="stylesheet">