<!DOCTYPE html>
<html>
<head>
    <title><?php if (isset($pageTitle)) echo($pageTitle) ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <script type="text/javascript" src="/resources/assets/bootstrap/js/bootstrap.min.js"></script>
    <link href="/resources/assets/bootstrap/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
<div class="container-fluid min-vh-80">
    <div class="modal-dialog text-center">
        <?php if (isset($isError) && $isError): ?>
            <div class="alert alert-danger" role="alert">
                <p class="text-danger"><?php echo $_SESSION['RESET_PASSWORD_ERROR']; ?></p>
            </div>
        <?php endif ?>

        <?php if (isset($isSuccess) && $isSuccess): ?>
            <div class="alert alert-success" role="alert">
                <p class="text-success"><?= $_SESSION["RESET_PASSWORD_SUCCESS"] ?></p>
            </div>
        <?php endif ?>

        <form method="post">
            <div class="card" style="margin-bottom: 30px">
                <div class="card-header">
                    <h3>Change password</h3>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" name="password" maxlength="32" class="form-control"><br/>
                    </div>
                    <div class="form-group">
                        <label for="password_repeat">Repeat password</label>
                        <input type="password" name="password_repeat" maxlength="32" class="form-control"><br/>
                    </div>
                    <div class="row">
                        <button type="submit" class="btn btn-primary" name="update">Save</button>
                        <a href="/profile" class="btn btn-secondary">Cancel</a>
                    </div>
                </div>
            </div>
        </form>

    </div>
</div>

</body>
</html>

