<html>
<head>
    <title>404 Not Found</title>
    <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/head.phtml" ?>
</head>
<body>
<?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/header/header.phtml" ?>
<div class="container">
    <div class="container">
        <div style="margin-top: 10%" class="col-xs-1" align="center">
            <h2>404 Not Found</h2>
            <h4>Oh you, there's nothing here!</h4>
            <img src="/resources/images/not-found.png" height="128px" alt="Not Found Pepe">
        </div>
    </div>
</div>
<?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/footer/footer.phtml" ?>
</body>
</html>