<!DOCTYPE html>
<html lang="en">
<head>
    <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/shared.phtml" ?>
</head>
<body>

<div class="container min-vh-80">
    <div class="col-sm-8">
        <h1>Reset password</h1>

        <?php if (isset($isError) && $isError): ?>
            <div class="alert alert-danger" role="alert">
                <p class="text-danger"><?= $_SESSION["PASSWORD_RESET_ERROR"] ?></p>
            </div>
        <?php endif ?>

        <?php if (isset($isSuccess) && $isSuccess): ?>
            <div class="alert alert-success" role="alert">
                <p class="text-success"><?= $_SESSION["PASSWORD_RESET_SUCCESS"] ?></p>
            </div>
        <?php endif ?>

        <form method="post">
            <div class="form-group">
                <label for="js-email">Please enter the E-Mail address you registered with</label>
                <input required id="js-email" type="email" name="email" maxlength="32"
                       class="form-control"><br/>
            </div>
            <div>
                <button type="submit" class="btn btn-primary" name="verifyReset">Reset</button>
            </div>
        </form>
    </div>
</div>
<?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/footer/footer.phtml" ?>
</body>
</html>
