<!DOCTYPE html>
<html lang="en">
    <head>
        <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/shared.phtml" ?>
    </head>
<body>

<div class="container min-vh-80">
    <div class="col-sm-8">

        <?php if (isset($isError) && $isError): ?>
            <div class="alert alert-danger" role="alert">
                <p class="text-danger"><?= $_SESSION["PASSWORD_RESET_ERROR"] ?></p>
            </div>
        <?php endif ?>

        <?php if (isset($isSuccess) && $isSuccess): ?>
            <div class="alert alert-success" role="alert">
                <p class="text-success"><?= $_SESSION["PASSWORD_RESET_SUCCESS"] ?></p>
            </div>
        <?php endif ?>

        <form method="post">
            <div class="card" style="margin-bottom: 30px">
                <div class="card-header">
                    <h3>Reset password</h3>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" name="password" maxlength="32" class="form-control"><br/>
                    </div>
                    <div class="form-group">
                        <label for="password_repeat">Repeat password</label>
                        <input type="password" name="password_repeat" maxlength="32" class="form-control"><br/>
                    </div>
                    <div class="row">
                        <button type="submit" class="btn btn-primary" name="update" style="margin-right: 10px">Save
                        </button>
                        <!--                        todo set different redirect depending on if comming from login or from profile-->
                        <a href="/profile" class="btn btn-secondary">Cancel</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/footer/footer.phtml" ?>
</body>
</html>
