<!DOCTYPE html>
<html lang="en">
    <head>
        <script type="text/javascript" src="/resources/assets/jquery/jquery.min.js"></script>
        <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/shared.phtml" ?>
        <script type="text/javascript" src="/views/chat/chat.js"></script>
        <link href="views/chat/chat.css" rel="stylesheet">
    </head>
    <body>

        <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/header/header.phtml" ?>
        <div class="container min-vh-80">
            <!-- Chat Header -->
            <div class="container">
                <h1>Private Chat</h1><br>
                <?php if(isset($isError) && $isError): ?>
                    <div class="alert alert-danger" role="alert">
                        <p class="text-danger"><?php echo $_SESSION['CHAT_ERROR']; ?></p>
                    </div>
                <?php endif ?>
                <?php if(isset($username)): ?>
                    <p>You are chatting with <?=$username?>.</p>
                <?php endif ?>
                <div hidden id="js-alert-box" class="alert alert-danger" role="alert">
                    <p id="js-alert-text" class="text-danger"></p>
                </div>
            </div>

            <!-- Messages and message history box -->
            <div id="js-history-box" class="container">
                <div class="msg-inbound bg-light">
                    <p>This is an inbound message.</p>
                </div>
                <div class="msg-outbound bg-primary">
                    <p>This is an outbound message.</p>
                </div>
            </div>

            <!-- Input and send button -->
            <div class="msg-send">
                <input id="js-message-box" type="text" name="message" placeholder="Enter your message..."
                       maxlength="2048" class="form-control"><br/>
                <button disabled id="js-send-button" class="btn btn-outline-primary">Send Message</button>
            </div>
        </div>
        <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/footer/footer.phtml" ?>
    </body>
</html>