<div class="container">
    <h1>500 Internal Server Error</h1>
    <p>
        A fatal error occured:
        <?php
            if (isset($isMessage) && $isMessage) {
                echo $_SESSION['INTERNAL_ERROR'];
            } else {
                echo "No additional information was given.";
            }
            $_SESSION['INTERNAL_ERROR'] = null;
        ?>
        <br/>
        Please contact the local site administrator with information on how to replicate this.<br/><br/>
        <a href="/">Back to home</a>
    </p>
</div>