<!DOCTYPE html>
<html lang="en">
<head>
    <title><?php if( isset($pageTitle)) echo($pageTitle)?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <script type="text/javascript" src="/resources/assets/bootstrap/js/bootstrap.min.js"></script>
    <link href="/resources/assets/bootstrap/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <h1>Register</h1><br>
        <p>Please enter following values to register.</p>

        <?php if(isset($isError) && $isError): ?>
            <div class="alert alert-danger" role="alert">
                <p class="text-danger"><?php echo $_SESSION['REGISTER_ERROR']; ?></p>
            </div>
        <?php endif ?>

        <?php if(isset($isSuccess) && $isSuccess): ?>
            <div class="alert alert-success" role="alert">
                <p class="text-success"><?php echo $_SESSION["REGISTER_SUCCESS"]; ?></p>
            </div>
        <?php endif ?>
        
        <form method="post">
            <div class="form-group">
                <label for="js-register-username">Username*</label>
                <input required id="js-register-username" type="text" name="username" class="form-control"><br/>
            </div>
            <div class="form-group">
                <label for="js-register-email">E-Mail*</label>
                <input required id="js-register-email" type="email" name="email" class="form-control"><br/>
            </div>
            <div class="form-group">
                <label for="js-register-password">Password*</label>
                <input required id="js-register-password" type="password" name="password" class="form-control"><br/>
            </div>
            <div class="form-group">
                <label for="js-register-firstname">First Name</label>
                <input id="js-register-firstname" type="text" name="first_name" class="form-control"><br/>
            </div>
            <div class="form-group">
                <label for="js-register-lastname">Last Name</label>
                <input id="js-register-lastname" type="text" name="last_name" class="form-control"><br/>
            </div>
            <div class="form-group">
                <label for="js-register-age">Age</label>
                <input id="js-register-age" type="number" name="age" class="form-control"><br/>
            </div>
            <p class="text-danger">*These fields are required.</p>
            <button id="js-register-submit" type="submit" class="btn btn-primary">Register</button>
        </form>
    </div>
</body>
</html>