<head>
    <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/shared.phtml" ?>
    <script type="text/javascript" src="profile.js"></script>
</head>
<body>
<?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/header/header.phtml" ?>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-4">
            <div class="card" style="width: 18rem;">
                <div class="card-header text-center">
                    <img class="rounded-circle" src="/resources/icons/user.ico" alt="User icon" height="150px">

                    <h5 class="card-title"><?= (isset($username)) ? $username : " " ?></h5>

                    <div class="button-container">

                        <?php if (isset($_SESSION["USER_ID"])) { ?>
                            <button class="btn btn-outline-primary" type="button"><a href="/profile-edit">Edit
                                    profile</a></button>
                        <?php } else { ?>
                            <button class="btn btn-outline-primary" type="button"><a href="#">Message</a></button>
                        <?php } ?>
                    </div>
                </div>

                <div class="card-body">
                    <h6 class="card-title"><?= (isset($firstName)) ? $firstName : " " ?></h6>
                    <h6 class="card-title"><?= (isset($lastName)) ? $lastName : " " ?></h6>
                    <h6 class="card-title"><?= (isset($email)) ? $email : " " ?></h6>

                </div>
            </div>
        </div>

        <div class="col-sm-8">
            <div class="card">
                <div class="card-header">
                    <!--TODO insert javascript to toggle between links-->
                    <ul class="nav nav-tabs card-header-tabs" id="tabs">
                        <li class="nav-item">
                            <a class="nav-link active" href="#created" role="tab" aria-controls="created"
                               aria-selected="true">Created events</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="booked" href="#booked" role="tab" aria-controls="booked"
                               aria-selected="false">Booked events</a>
                        </li>
                    </ul>
                </div>
                <div class="card-body">
                    <div class="tab-content">
                        <div class="tab-pane active" id="created" role="tabpanel">
                            <?php if (isset($events)):
                                foreach ($events as $event) {
                                    ?>
                                    <p><?= $event->title ?></p>
                                <?php } endif; ?>
                        </div>

                        <div class="tab-pane" id="booked" role="tabpanel" aria-labelledby="booked-tab">
                            <?php if (isset($booked)):
                                foreach ($booked as $b) { ?>
                                    <p><?= $b->title ?></p>
                                <?php } endif; ?>
                            <p>test</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/footer/footer.phtml" ?>
</body>
