<head>
    <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/head.phtml" ?>
</head>
<body>
<?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/header/header.phtml" ?>

<div class="container-fluid">
    <div class="col-sm-8">
    <form method="post">
        <div class="card" style="margin-bottom: 30px">
            <div class="card-header">
                <h3>Change personal information</h3>
            </div>
            <div class="card-body">
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" name="username" maxlength="32" class="form-control"><br/>
                </div>
                <div class="form-group">
                    <label for="first_name">First Name</label>
                    <input type="text" name="first_name" maxlength="32" class="form-control"><br/>
                </div>
                <div class="form-group">
                    <label for="last_name">Last Name</label>
                    <input type="text" name="last_name" maxlength="32" class="form-control"><br/>
                </div>
            </div>
        </div>

        <div class="card" style="margin-bottom: 30px">
            <div class="card-header">
                <h3>Change email address</h3>
            </div>
            <div class="card-body">
                <div class="form-group">
                    <label for="email">E-Mail</label>
                    <input type="email" name="email" maxlength="32" class="form-control"><br/>
                </div>
            </div>
        </div>

        <div class="card" style="margin-bottom: 30px">
            <div class="card-header">
                <h3>Change password</h3>
            </div>
            <div class="card-body">
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" name="password" maxlength="32" class="form-control"><br/>
                </div>
                <div class="form-group">
                    <label for="password_repeat">Repeat password</label>
                    <input type="password" name="password_repeat" maxlength="32" class="form-control"><br/>
                </div>
            </div>
        </div>

        <button type="submit" class="btn btn-primary" name="update">Save</button>
        <button class="btn btn-outline-primary"><a href="/profile">Cancel</a></button>
    </form>
    </div>
</div>

<?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/footer/footer.phtml" ?>
</body>