<!DOCTYPE html>
<html>
<head>
    <title><?php if( isset($pageTitle)) echo($pageTitle)?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <script type="text/javascript" src="/resources/assets/bootstrap/js/bootstrap.min.js"></script>
    <link href="/resources/assets/bootstrap/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
<div class="container-fluid">
    <div class="modal-dialog text-center">

        <div class="modal-content text-center">
            <div class="col-12">
                <h1>Login</h1>
                <h3>Event Booking</h3>

                <?php if(isset($isError) && $isError): ?>
                    <div class="alert alert-danger" role="alert">
                        <p class="text-danger"><?php echo $_SESSION['LOGIN_ERROR']; ?></p>
                    </div>
                <?php endif ?>

                <form method="post">
                    <div class="form-group">
                        <input type="text" class="form-control" name="emailOrId" placeholder="Username/E-Mail"
                               maxlength="32" required>
                    </div>
                    <div class="form-group">
                        <input type="password" class="form-control" name="password" placeholder="Password" maxlength="32" required>
                    </div>
                    <div>
                        <button type="submit" class="btn btn-primary" name="login">Login</button>
                    </div>
                </form>
                <div>
                    <a href="/register">Register</a>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>
