<!DOCTYPE html>
<html>
    <head>
        <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/shared.phtml" ?>
    </head>
    <body>
        <div class="container-fluid min-vh-80">
            <div class="modal-dialog text-center">
                <div class="modal-content text-center">
                    <div class="col-12">
                        <h1>Login</h1>
                        <h3>Event Booking</h3>

                        <?php if (isset($isError) && $isError): ?>
                            <div class="alert alert-danger" role="alert">
                                <p class="text-danger"><?php echo $_SESSION['LOGIN_ERROR']; ?></p>
                            </div>
                        <?php endif ?>

                        <form method="post">
                            <div class="form-group">
                                <input type="text" class="form-control" name="emailOrId" placeholder="Username/E-Mail"
                                       maxlength="32" required>
                            </div>
                            <div class="form-group">
                                <input type="password" class="form-control" name="password" placeholder="Password"
                                       maxlength="32" required>
                            </div>
                            <div>
                                <button type="submit" class="btn btn-primary" name="login">Login</button>
                            </div>
                        </form>
                        <div>
                            <a href="/register">Register</a>
                        </div>
                        <div>
                            <a href="/password-reset">Forgot password?</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>
