<!DOCTYPE html>
<html lang="en">
<head>
    <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/head.phtml" ?>
</head>
<body>
    <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/header/header.phtml" ?>
    <div class="container min-vh-80">
        <h1>Event Overview</h1><br>
        <a id="event-overview-create-button" href="/event-create" class="btn btn-primary mb-5">Create Event</a>
        <div class="row">
        <?php
            if (isset($events)):
                foreach ($events as $value) { ?>
                    <div class="col-6">
                        <div class="card m-2" style="width: 100%;">
                            <div class="card-body">
                                <h5 class="card-title"><?=$value->title?></h5>
                                <p class="card-text"><?=$value->description?></p>
                                <ul class="list-group list-group-flush mb-3">
                                    <?php if (!empty($value->location)): ?>
                                        <li class="list-group-item">Location: <?=$value->location?></li>
                                    <?php else: ?>
                                        <li class="list-group-item">Location: not specified</li>
                                    <?php endif; ?>
                                        <li class="list-group-item">Date: <?=$value->date?></li>
                                    <?php if (!empty($value->time)): ?>
                                        <li class="list-group-item">Time: <?=$value->time?></li>
                                    <?php else: ?>
                                        <li class="list-group-item">Time: not specified</li>
                                    <?php endif; ?>
                                    <?php if (!empty($value->price)): ?>
                                        <li class="list-group-item">Price: <?=$value->price?></li>
                                    <?php else: ?>
                                        <li class="list-group-item">Price: free</li>
                                    <?php endif; ?>
                                </ul>
                                <a href="/event-detail?event_id=<?=$value->event_id?>" class="btn btn-primary">Details</a>
                                <a href="/event-detail?event_id=<?=$value->event_id?>&book_event" class="btn btn-primary">Book Event</a>
                            </div>
                        </div>
                    </div>
                <?php }
            endif;
        ?>
        </div>
    </div>
    <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/footer/footer.phtml" ?>
</body>
<html>